/**
 * Enum com as disciplinas do Curso de Ciência da Computação
 */

export enum EDisciplina {

    PROGRAMACAO = "PROGRAMAÇÃO",
    ELETRONICA_DIGITAL = "ELETRÔNICA DIGITAL",
    MATEMÁTICA_DISCRETA = "MATEMÁTICA DISCRETA",

    //	FASE 2
    ALGEBRA_LINEAR_E_GEOMETRIA_ANALITICA = "ÁLGEBRA LINEAR E GEOMETRIA ANALÍTICA",
    ARQUITETURA_E_ORGANIZACAO_DE_COMPUTADORES = "ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES",
    LINGUAGENS_E_PARADIGMAS_DE_PROGRAMACAO = "LINGUAGENS E PARADIGMAS DE PROGRAMAÇÃO",

    //	FASE 3
    ESTRUTURAS_DE_DADOS = "ESTRUTURAS DE DADOS",
    SISTEMAS_OPERACIONAIS = "SISTEMAS OPERACIONAIS",

    REDES_DE_COMPUTADORES = "REDES DE COMPUTADORES",
    CALCULO = "CÁLCULO",
    CALCULO_NUMERICO = "CÁLCULO NUMÉRICO",

    //	FASE 3
    BANCO_DE_DADOS = "BANCO DE DADOS",
    COMPILADORES = "COMPILADORES",
    ENGENHARIA_DE_SOFTWARE = "ENGENHARIA DE SOFTWARE", 
    ESTATÍSTICA_E_PROBABILIDADE = "ESTATÍSTICA E PROBABILIDADE",

    //	Fase 6
    COMPUTACAO_GRAFICA = "COMPUTAÇÃO GRÁFICA", 
    SEGURANÇA_COMPUTACIONAL = "SEGURANÇA COMPUTACIONAL", 
    INTELIGENCIA_ARTIFICIAL = "INTELIGÊNCIA ARTIFICIAL", 
    SISTEMAS_DISTRIBUIDOS = "SISTEMAS DISTRIBUÍDOS",

    //	Fase 7
    MODELAGEM_E_SIMULACAO = "MODELAGEM E SIMULAÇÃO", 
    GERENCIA_DE_PROJETOS = "GERÊNCIA DE PROJETOS", 
    
    
    TEORIA_DA_COMPUTACAO = "TEORIA DA COMPUTAÇÃO",
	INFORMATICA_E_SOCIEDADE = "INFORMÁTICA E SOCIEDADE",
	GRAFOS = "GRAFOS",

}



