/**
 * Enum com as disciplinas do Curso de Ciência da Computação
 */

export enum EDisciplina {

    //	FASE 1
    INTRODUÇÃO_A_PROGRAMAÇÃO = "INTRODUÇÃO À PROGRAMAÇÃO",
    ELETRÔNICA_DIGITAL = "ELETRÔNICA DIGITAL",
    MATEMÁTICA_DISCRETA = "MATEMÁTICA DISCRETA",

    //	FASE 2
    PROGRAMAÇÃO_ORIENTADA_A_OBJETOS = "PROGRAMAÇÃO ORIENTADA A OBJETOS",
    ÁLGEBRA_LINEAR_E_GEOMETRIA_ANALÍTICA = "ÁLGEBRA LINEAR E GEOMETRIA ANALÍTICA",
    ARQUITETURA_E_ORGANIZAÇÃO_DE_COMPUTADORES = "ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES",
    INTRODUÇÃO_ÀS_REDES_DE_COMPUTADORES = "INTRODUÇÃO ÀS REDES DE COMPUTADORES",
    LINGUAGENS_E_PARADIGMAS_DE_PROGRAMAÇÃO = "LINGUAGENS E PARADIGMAS DE PROGRAMAÇÃO",

    //	FASE 3
    ESTRUTURAS_DE_DADOS = "ESTRUTURAS DE DADOS",
    SISTEMAS_OPERACIONAIS = "SISTEMAS OPERACIONAIS",
    DESENVOLVIMENTO_DE_APLICAÇÕES_ORIENTADAS_A_OBJETOS = "DESENVOLVIMENTO DE APLICAÇÕES ORIENTADAS A OBJETO",
    REDES_DE_COMPUTADORES = "REDES DE COMPUTADORES",
    CÁLCULO = "CÁLCULO",

    //	FASE 3
    LABORATÓRIO_DE_PROGRAMAÇÃO = "LABORATÓRIO DE PROGRAMAÇÃO",
    BANCO_DE_DADOS = "BANCO DE DADOS",
    COMPILADORES = "COMPILADORES",
    ENGENHARIA_DE_SOFTWARE = "ENGENHARIA DE SOFTWARE",
    ESTATÍSTICA_E_PROBABILIDADE = "ESTATÍSTICA E PROBABILIDADE",

    //	FASE 6
    COMPUTAÇÃO_GRÁFICA = "COMPUTAÇÃO GRÁFICA",
    SEGURANÇA_COMPUTACIONAL = "SEGURANÇA COMPUTACIONAL",
    INTELIGÊNCIA_ARTIFICIAL = "INTELIGÊNCIA ARTIFICIAL",
    SISTEMAS_DISTRIBUÍDOS = "SISTEMAS DISTRIBUÍDOS",

    //	FASE 7
    MODELAGEM_E_SIMULAÇÃO = "MODELAGEM E SIMULAÇÃO",
    GERÊNCIA_DE_PROJETOS = "GERÊNCIA DE PROJETOS",

}



